db:
    logging: false
mysql:
    host: localhost
    username: user
    password: user//pass
    database: node_and_friends
port: 4003
normalRowsPerPage: 3
timeout: 300000
authenUri: http://localhost:4002/
