db:
    logging: false
mongo:
    host: localhost:27017
    username: user
    password: user//pass
    database: node_and_friends
port: 4013
normalRowsPerPage: 3
timeout: 300000
authenUri: http://localhost:4012/
